### ISSUE TITLE
Some Headers other than the first are not marked as subsections

### ISSUE THREAD

**Issue by jay1891** [BrighterCommand/Docs#15]
Dear,

On readthedocs the index is a little unclear because some subsections have not a good styling, so e.g. 'Implementing a pipeline' is there multiple times but not clear in which context the title/item is relevant.

Currently there are some pull requests to solve an issue with the headers in the documentation. 

How can these changes be incorporated into the documentation?

Possibly there are also more. Can I review the docs to adjust them too, so they can be merged too?

Greetings,

**Comment by iancooper** [comment]
Closing as we now use GitBook
