### ISSUE TITLE
CancellationToken is a struct

### ISSUE THREAD

**Issue by SBFrancies** [BrighterCommand/Docs#20]
From https://github.com/BrighterCommand/Docs/blob/master/contents/AsyncDispatchARequest.md:

> The asynchronous methods: SendAsync, PublishAsync, and PostAsync all accept a CancellationTokenand pass this token down the pipeline. The parameter defaults to null where the call does not intend to cancel.

[CancellationToken](https://github.com/BrighterCommand/Docs/blob/master/contents/AsyncDispatchARequest.md) a struct so this isn't the case.

**Comment by iancooper** [comment]
OK it should be using default(CancellationToken). We should fix it.

**Comment by iancooper** [comment]
Fixed
