### ISSUE TITLE
Passing information to the caller

### ISSUE THREAD

**Issue by tomliversidge** [BrighterCommand/Docs#3]
I found the following information confusing in the docs on passing information to the caller (https://github.com/BrighterCommand/Docs/blob/master/source/DispatchingARequest.rst#passing-information-to-the-caller):

> In that case add a property to the Command that you can initialize from the Handler, for example create a NewEntityIdentity property in your command that you write the new entity’s identity to in the Handler, and then inspect the property in your Command in the calling code after the call to CommandDispatcher.Send() completes.

Implies that you can add a property to a command that is then updated inside the handler code. 

but then the following line  says you cannot do this:

> Note that you cannot use this strategy with CommandDispatcher.Send() as you have no way to update the Command in process.

Did i misunderstand something here?

**Comment by iancooper** [comment]
@tomliversidge Old, but thanks. We are on docs now and I will rephrase it
